# Generated by Django 6.0.7 on 2026-07-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Road', 'Road'), ('Garbage', 'Garbage'), ('Water', 'Water'), ('Electricity', 'Electricity'), ('Other', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('priority', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CivicReport',
        ),
    ]
