# Generated by Django 6.0.7 on 2026-07-24 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_reports', to='reports.report'),
        ),
        migrations.AddField(
            model_name='report',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
    ]
