# Generated by Django 6.0.7 on 2026-07-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_duplicate_of_report_is_duplicate'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='confidence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='severity_score',
            field=models.IntegerField(default=0),
        ),
    ]
